apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- db-staging-helmrelease.yaml
- github-instavote-provider.yaml
- instavote-gitrepository.yaml
- lfs269-helmrepository.yaml
- redis-staging-alert.yaml
- redis-staging-kustomization.yaml
- result-staging-helmrelease.yaml
- vote-staging-alert.yaml
- vote-staging-kustomization.yaml
